CREATE INDEX INDEXX ON pixels0 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels0 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels0 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels0 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels1 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels1 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels1 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels1 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels2 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels2 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels2 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels2 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels3 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels3 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels3 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels3 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels4 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels4 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels4 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels4 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels5 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels5 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels5 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels5 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels6 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels6 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels6 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels6 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels7 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels7 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels7 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels7 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels8 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels8 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels8 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels8 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels9 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels9 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels9 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels9 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels10 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels10 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels10 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels10 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels11 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels11 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels11 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels11 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels12 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels12 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels12 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels12 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels13 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels13 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels13 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels13 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels14 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels14 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels14 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels14 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels15 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels15 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels15 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels15 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels16 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels16 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels16 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels16 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels17 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels17 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels17 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels17 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels18 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels18 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels18 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels18 (address) USING BTREE;

CREATE INDEX INDEXX ON pixels19 (x) USING BTREE;
CREATE INDEX INDEXY ON pixels19 (y) USING BTREE;
CREATE INDEX INDEXCOLOR ON pixels19 (color) USING BTREE;
CREATE INDEX INDEXADDRESS ON pixels19 (address) USING BTREE;